### PR TITLE
Asynchronous I/O support and various tidy-ups

### PR DESCRIPTION
**Pull request by jhol**
This is my initial submission to add async support to cannelloni. So far the amount of testing I have done has been very minimal, and I have only tested IN transfers thus far.

### CODE REVIEW

**Comment by jhol** [comment]
@yomboprime I noticed this was necessary, because the synchronous design was dropping data in my use case where I have a 96Mbps stream.

**Comment by yomboprime** [comment]
Thanks! I'm reinstalling my system so I'll need one or two days to review this.

**Comment by jhol** [comment]
Just updated the commits with a few tidy-ups.

I've tested IN transfers a lot more extensively now, and it's working pretty perfectly.

With this design, it shouldn't be too difficult to later implement a bidirectional stream, where data is transferred both from stdin and stdout at once if there is any desire for such a feature.

The file I/O is still done synchronously, but eventually it might be beneficial to perform this part asynchronously also.

Also, I wonder if there is a way to use `splice(2)` to directly transfer the data from the input/output streams to/from USB so that transfers are done without having to copy to user-space and back.

**Comment by yomboprime** [comment]
Perfect! I was getting reallistically 25 MiB/s (as @RGD2 pointed out in an issue), but now I'm getting 45.4 MiB/s!. (46.8 in 16 bit wide bus) That is a 80% performance increase, a great improvement.

I have some corrections to make it work when limiting the number of bytes to transfer, plus other minor corrections. I will be doing them today.

**Comment by yomboprime** [comment]
I'll look at the ```splice``` function (I think I've never used it) About the bidirectionality seems good idea.

**Comment by yomboprime** [comment]
It seems the splice could be used indeed.

**Comment by jhol** [comment]
Thank you for taking care of all this. I'm really glad someone is looking after the project.

Using splice is an interesting concept, but I can imagine it might be tricky to get libusb and fd splicing to work together without treading on each other's toes - though I'm sure it can be figured out. With splice the performance would be top notch - cannelloni would only have to coordinate the kernel passing buffers from USB to/from file input/output.

The only way to go further would be to add support for io_uring, which would allow cannelloni to batch-trigger the splices without having to wake the main thread for every buffer. I can imagine this might be helpful if FX3 support is ever added.

**Comment by yomboprime** [comment]
Yes, perhaps we could lower CPU usage, which now is high (one core at 100% here).

**Pull request merged**
